### ISSUE TITLE
Add better evento logo 

### ISSUE THREAD

**Issue by codeAtNight009** [himalaya2Point0/EventoV2.0#3]
Evento logo as of now looks dull, find a better one and replace it
After updating make a pr
I will review the logo, if i find it good enough i would merge it else i would suggest you to use another logo

**Comment by Hussain6** [comment]
Can I handle this?

**Comment by shiv0403** [comment]
Please assign this issue to me @himalaya2Point0

**Comment by codeAtNight009** [comment]
> 
> 
> Can I handle this?

hussain bro comment on another issue 
I Will assign you that
